set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out[0]}]
set_property PACKAGE_PIN N19 [get_ports {vga_out[11]}]
set_property PACKAGE_PIN G19 [get_ports {vga_out[8]}]
set_property PACKAGE_PIN D17 [get_ports {vga_out[7]}]
set_property PACKAGE_PIN G17 [get_ports {vga_out[6]}]
set_property PACKAGE_PIN H17 [get_ports {vga_out[5]}]
set_property PACKAGE_PIN J17 [get_ports {vga_out[4]}]
set_property PACKAGE_PIN J18 [get_ports {vga_out[3]}]
set_property PACKAGE_PIN K18 [get_ports {vga_out[2]}]
set_property PACKAGE_PIN L18 [get_ports {vga_out[1]}]
set_property PACKAGE_PIN N18 [get_ports {vga_out[0]}]
set_property PACKAGE_PIN P19 [get_ports h_sync_out]
set_property PACKAGE_PIN R19 [get_ports v_sync_out]
set_property PACKAGE_PIN H1 [get_ports h_sync_in]
set_property PACKAGE_PIN K2 [get_ports v_sync_in]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync_in]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync_out]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync_in]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync_out]
set_property IOSTANDARD LVCMOS33 [get_ports vga_in]


set_property PACKAGE_PIN U16 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]

set_property IOSTANDARD LVCMOS33 [get_ports led_h]
set_property IOSTANDARD LVCMOS33 [get_ports led_v]

set_property PACKAGE_PIN H2 [get_ports vga_in]

set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_vga[0]}]
set_property PACKAGE_PIN V19 [get_ports led_vga]

set_property PACKAGE_PIN U16 [get_ports {led_vga[11]}]
set_property PACKAGE_PIN E19 [get_ports {led_vga[10]}]
set_property PACKAGE_PIN U19 [get_ports {led_vga[9]}]
set_property PACKAGE_PIN V19 [get_ports {led_vga[8]}]
set_property PACKAGE_PIN W18 [get_ports {led_vga[7]}]
set_property PACKAGE_PIN U15 [get_ports {led_vga[6]}]
set_property PACKAGE_PIN U14 [get_ports {led_vga[5]}]
set_property PACKAGE_PIN V14 [get_ports {led_vga[4]}]
set_property PACKAGE_PIN V13 [get_ports {led_vga[3]}]
set_property PACKAGE_PIN V3 [get_ports {led_vga[2]}]
set_property PACKAGE_PIN W3 [get_ports {led_vga[1]}]
set_property PACKAGE_PIN U3 [get_ports {led_vga[0]}]

set_property PACKAGE_PIN E19 [get_ports {led_vga[10]}]
set_property PACKAGE_PIN U19 [get_ports {led_vga[9]}]
set_property PACKAGE_PIN L1 [get_ports led_h]
set_property PACKAGE_PIN P1 [get_ports led_v]
set_property PACKAGE_PIN J19 [get_ports {vga_out[10]}]
set_property PACKAGE_PIN H19 [get_ports {vga_out[9]}]
